version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'admin' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
